### ISSUE TITLE
搞 IT

### ISSUE THREAD

**Issue by Laisky** [Laisky/Life#10]
2012 年毕业，在气象局做一个小预报员，2013 年转正，参与国家级项目一个，主持省级项目一个，小日子其实相当滋润。

不过因为老婆回国，所以辞职来上海。

2014.7 月正式转行进入 IT 领域，当年的状态相当水：
- 熟悉 Python 2.7 的基础语法规则
- 熟悉简单的 JavaScript（ES5） 和 CSS3

完…

Ps. 进入 IT 的原因是因为这行工资高

~~Ps. 而且我觉得我做任何一行都可以做的很好，那当然要选一行钱多的~~

Ps. 当然现在还处在被 IT 搞的状态

**Comment by Laisky** [comment]
2014.7 进入上海菜根科技有限公司

前半年做跟着超哥学习数据分析，顺带学代码，get 到的技能有：
- 严格的 PEP8 规范
- 单元测试的方法（unittest, TestCase, mock, fixtures, fake）
- IPython(shell & notebook)
- matplotlib
- nvd3
- pandas
- numpy
- scipy
- scikit-learn
- Python 3(asyncio)
- upstart
- aws
- ansible
- mongodb
- redis
- bash

最重要的是逐渐学习掌握了一套学习方法：
- 对于框架或工具，先海量而且迅速的阅读别人的介绍和心得，然后认真的阅读文档全文。
- 对于算法或方案，还是先迅速的阅读二手资料，然后去搜索原始论文，学习思路和后期的一些偏差处理。

而且意识到自己确实不是搞算法的料，我生性思维跳跃，难以沉浸于某一个专属领域内深入研究，我最擅长的是广泛的接触了解大量的知识，然后将其灵活的组织运用。

所以我将自己定性为一个_解决问题的工程人员_，我对自己的要求是：

### 创作时
- 遵循既有的最佳实践，少碰壁；
- 先实现，再优化。

### 解决问题时
- 迅速判断出问题的所在，并抽象出问题模式；
- 迅速的搜索出解决办法。

对的，我并不想去拓荒，我喜欢收割别人的既有成果，会有种极高效率的快感

---

不过，在菜根最大的收获是得以和一帮很优秀的人共事，作为一个刚进入这个行业的菜鸟，第一份工作就学会了优秀的人应该如何的看待和解决问题，我至今的行事风格和思维方式都在这一基础上进行模仿和提炼。

**Comment by Laisky** [comment]
然后因为要忙结婚、买房、装修，菜根的工作时间太长，所以换了家工作，2015.6.1 到了上汽。

## 读书

确实很闲，所以期间读了很多书：
- CSAPP
- CCNA
- 设计模式
- JavaScript 权威指南
- 数据挖掘导论
- Web 性能权威指南
- 七周七语言
- 以及几十本闲杂书目（比如《二战回忆录》）……

## 学习

然后开始系统的补全知识体系：
- [x] ECMAScript 6
- [x] CSS3
- [x] Python 3.5
- [x] 网络基础
- [x] Ubuntu 基础
- [x] CentOS 基础
- [x] 设计模式
- [x] 算法和数据结构

_*nix 基础指的是可以独自运维管理一台服务器，做好基础的安全防护和环境管理，并能进行一定的排错_

## 项目

在上汽第一年就是狂写各种 django 的内部系统，期间把 django、tornado 和 flask 换着用。有一些感触：
- flask 写小项目最快，做大型拆分还是很疼；
- tornado 疼度比较均匀，无论是小型还是大型就这么回事儿；
- django 几乎无痛，但是你懂得，不太 pythonic……

然后接了个 Docker 的项目，2016 年开始认真折腾 Docker

### 原生的
- [x] docker-engine
- [x] docker-machine
- [x] docker-registry
- [x] docker-compose
- [x] docker-swarm

### 第三方的
- [x] kubernetes
- [x] calico
- [x] cadvisor & influxdb & grafana
- [x] fluentd
- [x] rsyslog
- [x] pipeworks
- [x] etcd

## 前端

前端发展太快，系统了学习 ES6 后，还啃完了 angularjs 的文档（还提交了几个 typofix）。

不过后来觉得还是不喜 angularjs 这种大包大揽的，于是 4 月份开始学习 react
- [x] reactjs
- [x] gulp
- [x] jsx
- [x] flux
- [x] redux

## 微服务

上海写 Python 的人太少了，以后如果只是把自己定位成一个 Python 开发的话其实好的工作也很少。

如果想当一个 leader 的话，想要招到好的 Pythoner 也很难，所以从长远考虑，微服务是大势所趋。

但是毕竟微服务的门槛有一些小高，我也不能指望别人搭好一套架构，所以最好是自己具备微服务的整个技术栈。

这样我再出去的话，可以自己直接搭一整套框架，然后别人来写服务接入就行了，也不用担心具体招什么技术的人了。
- [ ] apigate
- [ ] registors

**Comment by zongyimin** [comment]
北京搞IT，python开发者不少，但是真的pythoner确实不多。
